name: Generate AI Video

on:
  workflow_dispatch:
    inputs:
      json_input:
        description: 'Paste your JSON array here'
        required: true
        type: string
        default: '{"global_settings": {"ratio": "16:9"}, "scenes": [{"scene_n": 1, "duration": 5, "bg_prompt": "A lone samurai standing on a mountain peak at sunrise", "motion": "zoom-in", "transition_file": "leftToRight.mp4", "transition_type": 1}, {"scene_n": 2, "duration": 5, "bg_prompt": "Close up of a katana sword reflecting the sun", "motion": "pan-right", "transition_file": "none", "transition_type": 1}]}'

jobs:
  build_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Save Input JSON Safely
      env:
        JSON_INPUT: ${{ github.event.inputs.json_input }}
      run: |
        echo "$JSON_INPUT" > input.json
        echo "=== Content of input.json ==="
        cat input.json
        echo "============================="

    - name: Run Video Generator Script
      run: python video_generator.py

    - name: Upload Final Video
      uses: actions/upload-artifact@v4
      with:
        name: Final-AI-Video
        path: final_video.mp4
